language: minimal

env:
  global:
    - BUILD_ACTION=default

stages:
  - name: default_job
  - name: example_job

jobs:
  include:
    - stage: default_job
      if: env("BUILD_ACTION") = default
      script:
        - echo "This is the default job"
    
    - stage: example_job
      if: env("BUILD_ACTION") = example
      script:
        - echo "This is the example job"
